[32mINFO    [0m root:test_mtx_cancel.py:31 取消成功